Repository jar285/mywebclass-simulation, pull requests merged in 2023-03, with the labels that each got.

#4 Added Live Site Deployment
  readme.md
Labels: documentation

#15 adding agile documentation
  agile.md
Labels: documentation

#20 add two links
  readme.md
Labels: DevOps

#22 ADD information the Conduct legal for the page web
  src/privacy.html
Labels: Legal Requirements/Compliances, Management

#28 add test for accesibility
  src/index.html
  tests/mywebclass_accessibility.spec.js
Labels: Accessibility Research

#30 add test for performance
  tests/mywebclass_performance.spec.js
Labels: Testing

#32 add test for sidebar
  tests/mywebclass_sidebar.spec.js
Labels: Testing

#41 the privacy content test
  tests/privacytest_content.spec.js
Labels: Legal Requirements/Compliances

#51 SEO Research and testing playwright
  tests/mywebclass_SEOTestingAndResearch.spec.js
Labels: SEO

#57 google analytics test
  tests/mywebclass_googleAnalytics.spec.js
Labels: documentation, Legal Requirements/Compliances, Google analytics

#69 Testing privacy playwright
  tests/mywebclass_privacy.spec.js
Labels: documentation, Testing, Responsive website

#75 Legal compliances and to test playwright for it
  src/privacy.html
  tests/mywebclass_privacyReadable.spec.js 
Labels: documentation, Testing, Legal Requirements/Compliances

#77 76 integrate automated testing into cicd pipeline for continuous monitoring
  tests/mywebclass_ci-cd-pipeline.spec.js
  tests/mywebclass_privacyReadable.spec.js
Labels: Testing

#79 test for webpack
  tests/mywebclass_webpacktest.spec.js
Labels: Testing

#38 add test for WCAG and W3C validation
  package-lock.json
  package.json
  src/index.html
  tests/mywebclass_validation.spec.js
Labels: Testing

#84 test performance for homepage
  tests/mywebclass_performance-homepage.spec.js
Labels: Testing

#78 Testing and quality assurance
  tests/mywebclass_metrics.spec.js
Labels: documentation, Testing

#86 test for box for email
  src/content.html
  tests/mywebclass_emailsub.spec.js
Labels: Testing

#90 Improve speed on website
  tests/mywebclass_speed.spec.js
Labels: documentation, Testing, SEO, Responsive website

#97 Extensively check for legal compliances
  tests/mywebclass_legalcompliances.spec.js
Labels: documentation, Testing, Legal Requirements/Compliances, Responsive website

#103 Added legal investigation for legal compliances
  tests/mywebclass_legalinvestigation.spec.js
Labels: documentation, Testing, Legal Requirements/Compliances, Responsive website

#108 Google analytics consent API
  tests/mywebclass_consentapi.spec.js
Labels: documentation, Testing, GDPR
